#!/bin/sh

export PATH="$APPDIR/usr/bin/:$PATH"

# Prevent Qt to load plugins from system directories
unset QT_PLUGIN_PATH

# Set the original working dir as the working dir.
# Ensures relative path arguments are resolved as expected.
cd $OWD
"$APPDIR"/usr/conda/bin/python "$APPDIR"/usr/conda/bin/picard "$@"
