#!/bin/sh

export PATH="${APPDIR}/usr/bin/:${PATH}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${APPDIR}/usr/conda/lib:${LD_LIBRARY_PATH}"

# Prevent Qt to load plugins from system directories
unset QT_PLUGIN_PATH

# Prevent OpenSSL 3.0 startup error
export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1

# Use SSL certificates from certifi package
SITE_PACKAGE_DIR=$(python -c 'import site; print(site.getsitepackages()[0])')
export SSL_CERT_FILE="${SITE_PACKAGE_DIR}/certifi/cacert.pem"

# Set the original working dir as the working dir.
# Ensures relative path arguments are resolved as expected.
cd $OWD
"$APPDIR"/usr/conda/bin/python "$APPDIR"/usr/conda/bin/picard "$@"
