#!/bin/sh

export PATH="${APPDIR}/usr/bin/:${PATH}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${APPDIR}/usr/conda/lib:${LD_LIBRARY_PATH}"

# Prevent Qt to load plugins from system directories
unset QT_PLUGIN_PATH

# Prevent OpsenSSL 3.0 startup error
export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1

# Set the original working dir as the working dir.
# Ensures relative path arguments are resolved as expected.
cd $OWD
"$APPDIR"/usr/conda/bin/python "$APPDIR"/usr/conda/bin/picard "$@"
